name: thirdeye
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.2.1
  flutter_svg: ^2.2.0
  shared_preferences: ^2.5.3
  http: ^1.4.0
  intl: ^0.20.2
  flutter_screenutil: ^5.9.0
  image_picker: ^1.1.2
  google_sign_in: ^6.2.1
  firebase_core: ^2.25.4
  firebase_auth: ^4.19.2
  path_provider: ^2.1.5
  share_plus: ^10.0.0
  firebase_storage: ^11.7.7
  supabase_flutter: ^2.10.3
  flutter_dotenv: ^6.0.0
  flutter_secure_storage: ^9.2.4
  jwt_decoder: ^2.0.1
  image_gallery_saver_plus: ^4.0.1
  permission_handler: ^11.0.1
  dio: ^5.3.3
  
  # Design and Animation Dependencies
  google_fonts: ^6.1.0
  lottie: ^3.1.0
  shimmer: ^3.0.0
  animate_do: ^3.3.4
  flutter_staggered_animations: ^1.1.1
  page_transition: ^2.1.0
  flutter_animate: ^4.5.0
  firebase_messaging: ^14.9.4
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.4"
  change_app_package_name: ^1.5.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

  adaptive_icon_background: "assets/icon_bg.png"
  adaptive_icon_foreground: "assets/logo.png"
  
flutter:
  uses-material-design: true

  assets:
    - assets/
    - .env
